apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helloworld-rollup.fullname" . }}-mongodb-pvc
  labels:
    {{- include "helloworld-rollup.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.config.mongodb.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.config.mongodb.persistence.size }}
