name: CI/CD Pipeline

on:
  push:
    branches: [ main, jupiter/cicd ]
    tags: [ 'v*' ]


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DEPLOY: ${{ secrets.DEPLOY }}
  USER_PRIVATE_ACCOUNT: ${{ secrets.USER_PRIVATE_ACCOUNT }}
  USER_ADDRESS: ${{ secrets.USER_ADDRESS }}
  SETTLEMENT_CONTRACT_ADDRESS: ${{ secrets.SETTLEMENT_CONTRACT_ADDRESS }}
  RPC_PROVIDER: ${{ secrets.RPC_PROVIDER }}
  SETTLER_PRIVATE_ACCOUNT: ${{ secrets.SETTLER_PRIVATE_ACCOUNT }}
  SERVER_ADMIN_KEY: ${{ secrets.SERVER_ADMIN_KEY }}
  PORT: ${{ secrets.PORT }}
  AUTO_SUBMIT: ${{ secrets.AUTO_SUBMIT }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Convert to lowercase
        id: lowercase
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug build args
        run: |
          echo "Build arguments:"
          echo "DEPLOY=${{ env.DEPLOY }}"
          echo "USER_ADDRESS=${{ env.USER_ADDRESS }}"
          echo "SETTLEMENT_CONTRACT_ADDRESS=${{ env.SETTLEMENT_CONTRACT_ADDRESS }}"
          echo "RPC_PROVIDER=${{ env.RPC_PROVIDER }}"
          echo "PORT=${{ env.PORT }}"
          echo "AUTO_SUBMIT=${{ env.AUTO_SUBMIT }}"
          echo "USER_PRIVATE_ACCOUNT=${{ env.USER_PRIVATE_ACCOUNT }}"
          echo "SETTLER_PRIVATE_ACCOUNT=${{ env.SETTLER_PRIVATE_ACCOUNT }}"
          echo "SERVER_ADMIN_KEY=${{ env.SERVER_ADMIN_KEY }}"

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          file: Dockerfile.ci
          tags: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:temp
          build-args: |
            DEPLOY=${{ env.DEPLOY }}
            USER_PRIVATE_ACCOUNT=${{ env.USER_PRIVATE_ACCOUNT }}
            USER_ADDRESS=${{ env.USER_ADDRESS }}
            SETTLEMENT_CONTRACT_ADDRESS=${{ env.SETTLEMENT_CONTRACT_ADDRESS }}
            RPC_PROVIDER=${{ env.RPC_PROVIDER }}
            SETTLER_PRIVATE_ACCOUNT=${{ env.SETTLER_PRIVATE_ACCOUNT }}
            SERVER_ADMIN_KEY=${{ env.SERVER_ADMIN_KEY }}
            PORT=${{ env.PORT }}
            AUTO_SUBMIT=${{ env.AUTO_SUBMIT }}
          no-cache: true

      - name: Get WASM MD5
        id: wasm-md5
        run: |
          docker create --name temp ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:temp
          docker cp temp:/app/wasm.md5 .
          docker rm temp
          MD5=$(cat wasm.md5 | tr '[:upper:]' '[:lower:]')
          echo "MD5=$MD5" >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}-${{ steps.wasm-md5.outputs.MD5 }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=long

      - name: Build and push final image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          file: Dockerfile.ci
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:latest
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ steps.wasm-md5.outputs.MD5 }}
          no-cache: true

      - name: Notify build result
        if: always()
        run: |
          echo "Image built and pushed: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}"